export type DependentPointHighlight = "DependentPointHighlight"
export type EndPointHighlight = "EndPointHighlight"
export type NothingHighlight = "NothingHighlight"
export type PointHighlightEnums = DependentPointHighlight | EndPointHighlight | NothingHighlight

return {
	DependentPointHighlight = "DependentPointHighlight":: DependentPointHighlight;
	EndPointHighlight = "EndPointHighlight":: EndPointHighlight;
	NothingHighlight = "NothingHighlight":: NothingHighlight;
}